# Generated by Django 6.0.4 on 2026-04-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rol', models.CharField(choices=[('duelist', 'Duelista'), ('controller', 'Controlador'), ('initiator', 'Iniciador'), ('sentinel', 'Centinela')], max_length=20)),
                ('imagen', models.URLField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
