# Generated by Django 6.0.4 on 2026-04-29 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valorant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('C', 'C'), ('Q', 'Q'), ('E', 'E'), ('X', 'Ultimate')], max_length=1)),
                ('icono', models.URLField(blank=True, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='valorant.agente')),
            ],
        ),
    ]
